In [1]:
import numpy as np

## Уровень 0

### a) Диагональная, ортогональная, но не единичная(!)

In [4]:
np.array([[np.cos(2), -np.sin(2)], [np.sin(2), np.cos(2)]])

array([[-0.41614684, -0.90929743],
       [ 0.90929743, -0.41614684]])

### b) Верхнетреугольная, ортогональная

In [30]:
A = np.array([[3, 1], [0, 0]])
A @ A.T

array([[10,  0],
       [ 0,  0]])

### c) Нижнетреугольная, ортогональная

In [ ]:
A = np.array([])

### d) Матрица, у которой определитель = 1, и все элементы не равны 0

In [38]:
A = np.array([[2, 3], [3, 5]])
np.linalg.det(A)

0.9999999999999991

In [67]:
m = np.array([[1, 2], [2, 3]])
l, v = np.linalg.eigh(m)

print(f'Собственные числа матрицы: {l[0]}, {l[1]},\nСобственные векторы матрицы: {v[0]}, {v[1]}')

Собственные числа матрицы: -0.2360679774997897, 4.23606797749979,
Собственные векторы матрицы: [-0.85065081  0.52573111], [0.52573111 0.85065081]


## Уровень 1

In [62]:
m = np.array([[1, 2], [2, 3]])

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])